export const bakeryProducts = [
  {
    id: "strawberry-shortcake",
    name: "Bánh Kem Dâu Tây Aura Signature",
    price: 320000,
    originalPrice: 400000,
    image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600&auto=format&fit=crop",
    rating: 4.9,
    isNew: true,
    isBestSeller: true,
    soldCount: 148,
    stock: 8,
    category: "Bánh Kem",
    description: "Chiếc bánh Signature đình đám của Aura Bakery. Được làm từ cốt bánh chiffon xốp mịn xen kẽ lớp kem sữa tươi hữu cơ ít béo, kết hợp cùng dâu tây tươi hữu cơ thu hoạch từ trang trại Đà Lạt chín mọng, ngọt lành.",
    ingredients: "Bột chiffon hảo hạng, kem tươi hữu cơ, dâu tây tươi Đà Lạt, vani hạt Madagascar, đường phèn tự nhiên.",
  },
  {
    id: "chocolate-truffle",
    name: "Bánh Kem Sô-cô-la Truffle Bỉ",
    price: 360000,
    originalPrice: 420000,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop",
    rating: 5.0,
    isNew: false,
    isBestSeller: true,
    soldCount: 236,
    stock: 5,
    category: "Bánh Kem",
    description: "Hương vị đam mê đậm đà dành cho tín đồ sô-cô-la thực thụ. Lớp nhân sô-cô-la truffle Bỉ nguyên chất 70% đắng nhẹ, béo ngậy xen kẽ giữa các lớp bánh xốp mềm ẩm mịn nướng lò hoàn hảo.",
    ingredients: "Sô-cô-la Bỉ nguyên chất 70%, kem bơ cacao Pháp, cốt bánh cacao mềm, bụi sô-cô-la trang trí.",
  },
  {
    id: "classic-croissant",
    name: "Bánh Croissant Bơ Pháp Cổ Điển",
    price: 450000, // Combo 6 cái hoặc bánh đặc biệt
    originalPrice: 45000, // Cần cẩn thận ở đây, 45k cho 1 cái bánh croissant. Hãy đặt giá phù hợp: 45000đ
    price: 45000,
    originalPrice: 55000,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop",
    rating: 4.8,
    isNew: true,
    isBestSeller: true,
    soldCount: 390,
    stock: 25,
    category: "Croissant",
    description: "Chiếc croissant nướng lò thủ công mỗi sáng sớm tại Aura. Lớp vỏ ngàn lớp óng ả giòn tan bên ngoài, ẩn giấu cấu trúc ruột bánh ẩm xốp mềm, dậy hương bơ Isigny nhập khẩu béo ngậy đậm chất Pháp.",
    ingredients: "Bột mì đa dụng Pháp, bơ lạt Isigny Normandy, men sống tự nhiên, mật ong hoa nhãn.",
  },
  {
    id: "tiramisu-royal",
    name: "Bánh Tiramisu Hoàng Gia Ý",
    price: 85000,
    originalPrice: 95000,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop",
    rating: 4.9,
    isNew: false,
    isBestSeller: true,
    soldCount: 310,
    stock: 12,
    category: "Bánh Ngọt",
    description: "Một tác phẩm nghệ thuật tinh tế từ Ý. Cốt bánh sampa (ladyfingers) được nhúng ngập trong ly espresso đậm đặc thơm lừng kèm rượu hương hạnh nhân amaretto, phủ lớp kem phô mai mascarpone béo ngậy.",
    ingredients: "Phô mai Mascarpone Ý, rượu Amaretto, cà phê Espresso đặc biệt, trứng gà hữu cơ, bột ca cao.",
  },
  {
    id: "matcha-crepe",
    name: "Bánh Mille Crepe Matcha Nhật Bản",
    price: 89000,
    originalPrice: 110000,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop",
    rating: 4.7,
    isNew: true,
    isBestSeller: false,
    soldCount: 95,
    stock: 10,
    category: "Bánh Ngọt",
    description: "Hơn 20 lớp bánh crepe mỏng như lụa xếp chồng đan xen lớp kem tươi tươi mát vị matcha Uji nhập khẩu trực tiếp từ Nhật Bản. Bánh thanh mát, ít ngọt, ngọt ngào dễ chịu tan ngay trong miệng.",
    ingredients: "Bột matcha Uji cao cấp, kem tươi hữu cơ, trứng gà, bột Crepe hảo hạng.",
  },
  {
    id: "red-velvet",
    name: "Bánh Red Velvet Nhung Đỏ Quý Phái",
    price: 90000,
    originalPrice: 90000,
    image: "https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=600&auto=format&fit=crop",
    rating: 4.8,
    isNew: false,
    isBestSeller: false,
    soldCount: 84,
    stock: 15,
    category: "Bánh Ngọt",
    description: "Màu đỏ nhung rực rỡ tượng trưng cho sự may mắn và hạnh phúc. Chiếc bánh ẩm mịn với vị cacao tinh tế, kết hợp hoàn hảo cùng lớp phủ phô mai kem cream cheese chua béo đậm vị.",
    ingredients: "Phô mai kem Cream Cheese Anchor, bột cacao hữu cơ, vani, bơ sữa tự nhiên.",
  },
  {
    id: "almond-croissant",
    name: "Bánh Croissant Hạnh Nhân Nướng Lò",
    price: 49000,
    originalPrice: 60000,
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&auto=format&fit=crop",
    rating: 4.7,
    isNew: false,
    isBestSeller: false,
    soldCount: 160,
    stock: 2,
    category: "Croissant",
    description: "Bánh croissant ngàn lớp giòn rụm được bơm đầy kem hạnh nhân frangipane thơm bùi ngọt ngào, phía trên rắc đầy hạnh nhân lát nướng vàng thơm lừng và phủ một lớp đường bột mỏng thanh khiết.",
    ingredients: "Bơ Pháp ngàn lớp, hạt hạnh nhân nghiền nhuyễn, bột hạnh nhân, kem trứng béo sữa.",
  },
  {
    id: "combo-royal-tea",
    name: "Combo Trà Hoa Chiều Hoàng Gia Aura",
    price: 189000,
    originalPrice: 240000,
    image: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=600&auto=format&fit=crop",
    rating: 4.9,
    isNew: true,
    isBestSeller: true,
    soldCount: 78,
    stock: 4,
    category: "Combo",
    description: "Lựa chọn tinh tế cho buổi hẹn hò lãng mạn. Combo bao gồm 4 chiếc bánh macarons đa sắc hương vị thanh tao nhập từ Pháp cùng 1 bình trà hoa cúc mật ong hảo hạng làm ấm cơ thể.",
    ingredients: "4 bánh Macarons Pháp, bình trà hoa cúc hữu cơ, mật ong rừng tự nhiên.",
  }
];
